### ISSUE TITLE
Auto refresh for flow stats page

### ISSUE THREAD

**Issue by azhermughal** [of-ng/web-ui#1]
Currently graph page is not auto refreshed. We need to add an auto Refresh button on the graph page. Button can take input e.g. 15/30/45/60 seconds input.

**Comment by azhermughal** [comment]
Added in file plot_flow.html, fixed.
<meta HTTP-EQUIV="refresh" CONTENT="15">

**Comment by beraldoleal** [comment]
if you fixed... please commit.
