### ISSUE TITLE
All Flows Link

### ISSUE THREAD

**Issue by azhermughal** [of-ng/web-ui#3]
It should open the page in new browser window.

**Comment by azhermughal** [comment]
Solved by adding target="_blank" at line 165 in static/assets/templates/switch-details.handlebars:

                    <th><a target="_blank" href="/plot_flow.html?node={{node_id}}&table={{table_id}}&clean_id={{clean_id}}"><i class="fa fa-area-chart"></i></a>

**Comment by beraldoleal** [comment]
if you fixed... please commit.
